= Banana-i18n-KMP
:link-repository: https://github.com/bitPogo/kmock-playground
:project-version: 0.1.0
:doctype: article
:!showtitle:
:toc: macro
:toclevels: 2
:toc-title:
:icons: font
:imagesdir: assets/images
ifdef::env-github[]
:warning-caption: :warning:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
endif::[]

++++
<div align="center">
    <p><!-- PROJECT TITLE -->
        <h3>Antibytes  KMock Playground</h3>
    </p>
    <p><!-- PROJECT DESCRIPTION -->
        TODO
    </p>
    <p><!-- PROJECT DOCUMENTATION -->
        <a href="README.adoc"><strong>Explore the docs »</strong></a>
    </p>
    <p><!-- PROJECT ISSUES/FEATURES -->
        <a href="https://github.com/bitPogo/kmock-playground/issues">Report Bug</a>
        ·
        <a href="https://github.com/bitPogo/kmock-playground/issues">Request Feature</a>
    </p>
    <p><!-- PROJECT BADGES see badges.adoc how to change them -->
        <a href="https://github.com/bitPogo/kmock-playground/actions">
            <img src="https://github.com/bitPogo/kmock-playground/actions/workflows/ci-latest-version.yml/badge.svg" alt="Latest Version"/>
        </a>
    </p>
</div>
++++

[discrete]
=== Table Of Contents

toc::[]

== About The Project

Coming soon.

=== Dependencies

Coming soon.

== Installation

Coming soon.

=== Consume GitHub Packages

Coming soon.

==== Setup Maven Repository

Coming soon.

==== Common

Coming soon.

==== Android

Coming soon.

== Building and Working with the code base

There are several requirements for building the project.

=== Requirements

Coming soon.

=== Built With

* link:https://kotlinlang.org/docs/reference/mpp-intro.html[Kotlin Multiplatform]

== Contributing

You want to help or share a proposal? You have a specific problem? Read the following:

* link:CODE-OF-CONDUCT.adoc[Code of conduct] for details on our code of conduct.
* link:CONTRIBUTING.adoc[Contributing] for details about how to report bugs and propose features.

== Copyright and License

Copyright (c) 2021 Matthias Geisler (bitPogo) / All rights reserved.

Please refer to our link:LICENSE[License] for further details.
